version: '3.3'
services:
  service:
    build: ../../..
    image: ravidgontov/marketplace-service:latest
    restart: always
    ports:
      - '2000:2000'
    expose:
      - '2000'
    environment:
      DbUrl: "jdbc:mysql://host.docker.internal:3306/"
      DbParams: "?serverTimezone=UTC&useLegacyDatetimeCode=FALSE&useSSL=FALSE&allowPublicKeyRetrieval=TRUE"
      DbName: "db"
      DBusername: "admin"
      DBpassword: "admin123"
      LOGGER_APPENDER: "Text"
      SPRING_CONFIG_NAME: "application"
      SPRING_CONFIG_LOCATION: "/lib/properties/"
    depends_on:
      db:
        condition: service_healthy
  db:
    build: ../../../db
    image: ravidgontov/marketplace-db:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
volumes:
  my-db: